Fix workflow

diff --git a/.github/workflows/release_candidate.yaml b/.github/workflows/release_candidate.yaml
--- a/.github/workflows/release_candidate.yaml
+++ b/.github/workflows/release_candidate.yaml
@@ -43,40 +43,28 @@ jobs:
           if [ ! -f ".changeset/pre.json" ] || [ "$(jq -r ".mode" .changeset/pre.json)" = "exit" ]; then
             echo "Enter the pre-release mode"
             yarn dlx @changesets/cli pre enter beta
+            # Create pre-release versions (update CHANGELOG and package.json files)
             yarn dlx @changesets/cli version
-            if [ "$(jq -r '.changesets | length' .changeset/pre.json)" -eq 0 ]; then
-              echo "The 'changesets' array is empty."
-              echo "::error title=Missing changeset files::Add one (or more) changeset files before entering the pre-release mode."
-              exit 1
-            else
-              echo "Changes detected in the .changeset folder:"
-            fi
+            #if [ "$(jq -r '.changesets | length' .changeset/pre.json)" -eq 0 ]; then
+            #  echo "The 'changesets' array is empty."
+            #  echo "::error title=Missing changeset files::Add one (or more) changeset files before entering the pre-release mode."
+            #  exit 1
+            #else
+            #  echo "Changes detected in the .changeset folder:"
+            #fi
             # Ensure the pre.json is pushed to the repository
             echo "Pushing pre-release state..."
-            git add .changeset/pre.json
-            git commit -m "Enter pre-release mode"
+            git add .
+            git commit -m "Enter pre-release mode and version packages"
+            echo "Publishing pre-release packages..."
+            yarn dlx @changesets/cli tag
+            git push --follow-tags
+            echo "Exiting pre-release mode"
+            yarn dlx @changesets/cli pre exit
+            git add .
+            git commit -m "Exit prerelease mode"
             git push origin HEAD:${{ github.ref_name }}
           else
             echo "::debug::Already in pre-release mode"
             exit 1
           fi
-
-      - name: Fetch latest changes
-        run: git pull origin ${{ github.ref_name }}
-
-      - name: Create Release Pull Request or Publish to npm
-        id: changesets
-        uses: changesets/action@c8bada60c408975afd1a20b3db81d6eee6789308 # v1.4.9
-        with:
-          version: yarn run version
-          publish: yarn run release
-          setupGitUser: false
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT }}
-
-      - name: Exit pre-release mode
-        run: |
-          yarn dlx @changesets/cli pre exit
-          git add .changeset/pre.json
-          git commit -m "Enter pre-release mode"
-          git push origin HEAD:${{ github.ref_name }}
