Check if there are changeset files

diff --git a/.github/workflows/release_candidate.yaml b/.github/workflows/release_candidate.yaml
--- a/.github/workflows/release_candidate.yaml
+++ b/.github/workflows/release_candidate.yaml
@@ -39,9 +39,16 @@ jobs:
       - name: Check pre state and enter pre mode if needed
         id: check_pre_state
         run: |
+          # If pre.json does not exist or it is in "exit" mode
           if [ ! -f ".changeset/pre.json" ] || [ "$(jq -r ".mode" .changeset/pre.json)" = "exit" ]; then
             echo "Enter the pre-release mode"
             yarn dlx @changesets/cli pre enter beta
+            # Check there are changeset files for the pre release
+            if [ "$(jq -r '.changesets | length' .changeset/pre.json)" -eq 0 ]; then
+              echo "The 'changesets' array is empty."
+              echo ":: error title=Missing changeset files:: Add one (or more) changeset files before entering the pre-release mode."
+              exit 1
+            fi
             # Ensure the pre.json is pushed to the repository
             echo "Pushing pre-release state..."
             git add .changeset/pre.json
